version: '3'
services:
  payment:
    build: ./payment
    image: payment-service:latest
    container_name: payment
    ports:
      - "4000:4000"

  order1:
    build: ./order
    image: order-service:latest
    container_name: order1
    ports:
      - "5000:5000"

  order2:
    build: ./order
    image: order-service:latest
    container_name: order2
    ports:
      - "7000:5000"
